config/routes.rb
Rails.application.routes.draw do
  get 'users/homepage'
  post 'users/homepage' => "users#homepage"

  get 'users/settings'
  post 'users/settings' => 'users#settings'

  get 'users/login_shield'
  post 'users/login_shield' => "users#login_shield"

  get '/', to: redirect('users/login')

  get 'users/login'
  post 'users/login' => 'users#login'
  
  get 'users/email_update'
  post 'users/email_update' => 'users#email_update'

  get 'tickets/tickets_tasks'
  post 'tickets/tickets_tasks' => 'tickets#tickets_tasks'

  get 'users/update_mobile'
  post 'users/update_mobile' => 'users/update_mobile'

  get 'users/password_recovery'
  post 'users/password_recovery' => 'users/password_recovery'

  resources :users do
    post :verify, on: :collection, as: :verify
    post :login_verify, on: :collection, as: :login_verify
    post :tryagain, on: :collection, as: :tryagain
    post :two_factor_switch, on: :collection, as: :two_factor_switch
    post :email_change, on: :collection, as: :email_change
    post :save_mobile_update, on: :collection, as: :save_mobile_update
    post :admin_filter, on: :collection, as: :admin_filter
    post :password_reset, on: :collection, as: :password_reset
    post :set_new_password, on: :collection, as: :set_new_password
    member do
      put "mark_as_read" => "users#mark_as_read"
      get :confirm_email
      get :change_forgoten_password
    end
  end

  resources :tickets do 
    post :watch, on: :collection, as: :watch
    post :unwatch, on: :collection, as: :unwatch
    post :imWorkingOnIt, on: :collection, as: :imWorkingOnIt
    post :solved, on: :collection, as: :solved
  end

  resources :progresss do
    post :add_subtasks, on: :collection, as: :add_subtasks
    post :assing_task, on: :collection, as: :assing_task
  end
  
  resources :comments do
      post :reply, on: :collection, as: :reply
      post :employee_reply, on: :collection, as: :employee_reply
  end

  get "/resend_eimail_confirmation" => "users#resend_eimail_confirmation", :as => "resend_eimail_confirmation"
  get "/log_out" => "users#logout", :as => "log_out"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy email_update update_mobile]
  include UsersHelper
  # GET /users or /users.json
  def index
    @users = User.all
  end

  def two_factor_switch
   if  Settings.two_factor_status_switch(User.find_by_id(session[:user_id]),params[:commit]) == true
    redirect_back(fallback_location: users_path)
   else
    redirect_back(fallback_location: users_path, :notice => "")
   end
  end

  def email_update
    
  end

  def mark_as_read
    @notification = Notification.where(user_id: session[:user_id]).unread
    @notification.update_all(status: true) if !@notification.empty?
    respond_to do |format|
        format.js
    end
end

def password_reset
  user = User.reset_forgoten_password(User.find_by_email(user_params[:email]))
  if user 
    flash[:success] = "A recovery email have been send!"
    redirect_to users_login_path
  else
    flash[:error] = "Something went wrong, please try again!"
    redirect_to users_login_path
  end
end

def  resend_eimail_confirmation
  User.resend_email_activation_link(session[:user_id])
  redirect_back(fallback_location: users_path)
end

  def email_change
   status_code =  User.change_email(User.find_by_id(session[:user_id]),user_params[:old_email],user_params[:new_email],user_params[:email_confirmation])
    if status_code == 001
      redirect_back(fallback_location: users_path, :notice => "Old Email doesn't match with the user current Email")
    elsif status_code == 002
      redirect_back(fallback_location: users_path, :notice => "New Email is the same with the user current Email")
    elsif status_code == 004
      redirect_back(fallback_location: users_path, :notice => "Email isn't valid")
    elsif status_code == 005
      redirect_back(fallback_location: users_path, :notice => "This email is already used")
    else
      redirect_back(fallback_location: users_path, :notice => "Updated!")
    end
  end


  def update_mobile

  end

  def save_mobile_update
   if  User.save_mobile_details(User.find_by_id(session[:user_id]),params[:countryCode],user_params[:mobile])
    redirect_back(fallback_location: users_path, :notice => "Mobile number updated!")
   else
    redirect_back(fallback_location: users_path, :notice => "Something went wrong!")
   end
  end

  # GET /users/1 or /users/1.json
  def show
  end

  def admin_filter
    if request.referrer.match(/([^\/]+$)/).to_s =~ /tickets.*\b/
      redirect_to tickets_path(department: user_params[:admin_filter])
    else
      redirect_to users_homepage_path(department: user_params[:admin_filter])
    end
  end

  def homepage
    @department = helpers.setUpCookie(params[:department])
    @user = User.find_by_id(session[:user_id])
    @tickets = helpers.dynamic_index(@user, nil, nil,  @department)
  end

  def settings
    @user = User.find_by_id(session[:user_id])
  end

  def login

  end

  def login_shield

  end

  def tryagain
    user =  helpers.resend(User.find_by_email(session[:user_email]))
    if !user
      flash[:error] = "You Session has expired!"
      session[:user_email] = nil
      redirect_to users_login_url
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def logout
    session[:user_id] = nil
    redirect_to users_login_path , :notice => "Logged out!"
  end


  def confirm_email
    
    user = User.find_by_id(Token.find_by_email_token(params[:id]).user_id) if Token.find_by_email_token(params[:id]) != nil
    if user
      user.email_activate
      flash[:success] = "Your email has been confirmed.
      Please sign in to continue."
      redirect_to users_login_path
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to users_login_path
    end
end


def change_forgoten_password
  user = User.find_by_id(Token.find_by_password_token(params[:id]).user_id) if Token.find_by_password_token(params[:id]) != nil
  if user
    helpers.setUpPasswordResetCookie(params[:id])
    redirect_to users_password_recovery_path
  else
    redirect_to users_login_path
  end
end

def password_recovery
 # user = User.find_by_id(Token.find_by_password_token(cookies[:token]).user_id)
  if cookies[:token] == nil
    redirect_to users_login_path
  end
end

def set_new_password
  if cookies[:token] == nil
    redirect_to users_login_path
  else
    user = User.update_password(User.find_by_id(Token.find_by_password_token( Base64.decode64(cookies[:token])).user_id), user_params[:password], user_params[:password_confirmation])
    if user 
      flash[:success] = "Password Updated"
      redirect_to users_login_path
    else
      redirect_to users_password_recovery_path
    end
  end
end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.settings.destroy
    @user.token.destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :encrypted_password, :password, :password_confirmation, :admin_filter, :email, :mobile, :salt, :group, :email_comfirmed, :two_factor, :loginpass, :old_password, :old_email, :new_email, :email_confirmation, :countryCode)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def  UserGroupIsAdmin(user)
    if user.blank?
        false
    else
        true
    end
  end

  def two_factor_status(user)
    if user.settings.two_factor == true
      session[:user_email] = user.email
      send_second_code(user)
    else
      false
    end
  end


  def send_second_code(user)
    User.get_one_time_code(user.email)
    true
  end


    
  def auth_token_check(user_email,second_code)
    user = User.find_by_email(user_email)
    second_code =  Base64.encode64(second_code)
    if user.token.password_token == second_code && user.token.password_time + 3*60  > Time.now
     user.token.password_token
     user.token.password_time
     user.token.save(:validate => false)
     user
  elsif user.token.password_token == second_code && user.token.password_time + 3*60 < Time.now
      user.token.password_token
      user.token.password_time
      user.save(:validate => false)
      false
  elsif user.token.password_token != second_code && user.token.password_time + 3*60 < Time.now
      false
  else
   nil
  end

end

  def email_verifycation_check(user)
    user_email_status = User.find_by_id(user)
      status = user_email_status.settings.email_comfirmed if user_email_status != nil
      if !status
        true
  end
end


=begin def resend_verification_email
content_tag :div, class: "email_warrning" do
  content_tag :h4 do
      content_tag :span, class: "badge badge-danger" do
  content_tag :a do
    content_tag :href do
      link_to "Resend", users_login_path
    end
  end
    end
  end
end
end
=end

def get_user_data
 user = User.find_by_id(session[:user_id])
 if user.settings.two_factor == true
  yield("Enabled")
  "success"
 else
  "danger"
 end
end


def settings_two_factor_status(status = "Disabled")
  if status == false
    "Disabled"
  else
    "Enabled"
  end
end

def resend(user)
  if user.token.password_time + 60*60 < Time.now
    nil
  else
    user.token.password_time = Time.now
    user.token.save(:validate => false)
    UserMailer.two_factor_auth_code(User.find_by_email(user.email)).deliver
  end
end

def status_message(status)
  if status == "Updated!" || status == "Mobile number updated!"
    "success"
  else
    "danger"
  end
end


def in_progress(user,tickets,department)
i = 0
if user.group == "User"
  tickets.each do |ticket|
    if ticket.user == user.username && ticket.statusinfo == "In Progress" && ticket.status != false
      i +=1
    end
  end
  return i

elsif  user.group != "Admin"
  tickets.each do |ticket|
    if ticket.ticketDepartment == user.group && ticket.readed == false && ticket.statusinfo == "In Progress"
      i +=1
    end
  end
  return i

elsif user.group == "Admin" &&   department == nil
  tickets.each do |ticket|
    if ticket.statusinfo == "In Progress" && ticket.status != false
      i +=1
    end
  end
  return i

elsif user.group == "Admin" &&  department != nil
  tickets.each do |ticket|
    if ticket.ticketDepartment == department && ticket.statusinfo == "In Progress" && ticket.status != false
      i +=1
    end
  end
  return i
  end
end


def new_tickets_and_unopened(user,tickets,department)
  i = 0
  if user.group == "User"
   # puts tickets.status
   tickets.each do |ticket|
    if ticket.user == user.username
      i += 1
    end
  end
    return i

  elsif user.group == "Admin" &&  department == nil
    tickets.each do |ticket|
      if ticket.readed == false
        i +=1
      end
    end
    return i

  elsif user.group == "Admin" &&  department != nil
    tickets.each do |ticket|
      if ticket.ticketDepartment == department && ticket.readed == false
        i +=1
      end
    end
    return i

  elsif  user.group != "Admin" 
    tickets.each do |ticket|
      if ticket.ticketDepartment == user.group && ticket.readed == false
        i +=1
      end
    end
    return i
  
  end
end


def wont_fix_tickets(user,tickets,department)
  i = 0
if  user.group == "User" 
  tickets.each do |ticket|
    if ticket.user == user.username && ticket.status == false && ticket.statusinfo == "Won't fix"
      i +=1
    end
  end
  return i

elsif  user.group != "Admin" 
  tickets.each do |ticket|
    if ticket.ticketDepartment == user.group && ticket.status == false && ticket.statusinfo == "Won't fix"
      i +=1
    end
  end
  return i

elsif  user.group == "Admin" &&  department == nil
  tickets.each do |ticket|
    if  ticket.status == false && ticket.statusinfo == "Won't fix"
      i +=1
    end
  end
  return i

elsif  user.group == "Admin" && department != nil
  tickets.each do |ticket|
    if ticket.ticketDepartment == department && ticket.status == false && ticket.statusinfo == "Won't fix"
      i +=1
    end
  end
  return i 

  end
end

def solved_tickets(user,tickets,department)
i = 0
if  user.group == "User"
  tickets.each do |ticket|
    if ticket.user == user.username && ticket.status == false
      i +=1
    end
  end
  return i

elsif  user.group != "Admin"
  tickets.each do |ticket|
    if ticket.ticketDepartment == user.group && ticket.status == false
      i +=1
    end
  end
  return i

elsif user.group == "Admin" && department == nil
  tickets.each do |ticket|
    if ticket.status == false
      i +=1
    end
  end
  return i

elsif user.group == "Admin" && department != nil
  tickets.each do |ticket|
    if ticket.ticketDepartment == department && ticket.status == false
    i += 1
  end
end
return i

  end
end
end

def admin_dropdown_fil
  form_tag(controller: "users", action: "admin_filter") do
    groups =  User.where.not(group: ["User","Admin"]).distinct.pluck(:group)
        raw groups.length.times.map { |group| content_tag(:button, value: groups[group], class: "dropdown-item", name: "user[admin_filter]", id: "admin_filter", onclick: "addrows();" ) { groups[group] } }.join
      end
end


def get_notification(user)
  unreaded = []
  #if user.group != "Admin"
    unreaded << Notification.where(:status => "false", :user_id => user.id ).ids 
  #end
  return unreaded.flatten.length

end

def get_notification_info(user)
  notifications =  Notification.order('created_at DESC').where(:user_id => user.id)
  if notifications.empty?
    return nil
  else
     return notifications
  end

end

app/views/users/_update_password.html.erb
<center>
    <div class="container" id="edit_user">

<h1>Change Password</h1>
<%= form_with(model: user, remote: true) do |form| %>
  <% if user.errors.any? %>
    <div class="errors" id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="edit_user">
        <div class="item">
  <div class="password_restore_form">
<div class="password_rules">
<p><center><strong id="edit_title">Password Rules</strong></p>
<p><li id="password_length">Password must be at least 8 characters</li></p>
<p><li id="password_match">Password doesn't match with password confirmation</li></p>

</center>
      <!-- Username -->
       <div class="item">
      <div class="control-group">
    <%= form.label :username, "Username" %>
    <%= form.text_field :username, :disabled => true, class: "form-control", id: "old_password" %>
  </div>
  
    <div class="control-group">
      <!-- Password-->
        <%= form.label :old_password, "Old Password *" %>
        <%= form.password_field :old_password, id: "old_password", class: "form-control", placeholder: "Old Password" %>      <div class="controls">
        <p class="help-block"></p>
    </div>
 
    <div class="control-group">
      <!-- Password-->
        <%= form.label :password, "New Password *" %>
        <%= form.password_field :password, id: "password", class: "form-control", placeholder: "New Password" %>      <div class="controls">

    </div>
 
    <div class="control-group">
      <!-- Password -->
        <%= form.label :password_confirmation, "Password confirmation *" %>
        <%= form.password_field :password_confirmation, class: "form-control", id: "password_comf", placeholder: "Password confirmation" %>
      <br>
    </div>
        <%= form.submit "Update" %>
    </div>
    </div>

</center>
<%= javascript_pack_tag 'password_rules_check' %>

  <% end %>

app/views/users/edit.html.erb
<%= render 'update_password', user: @user %>

app/views/users/homepage.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Tickets</title>


</head>

<body>
<!-- Button trigger modal -->

      <%if @user.group != "User" %>
    <div class="content">
    <br>
     <br>
      <br>
            <h3><span class="badge badge-secondary">Tickets for <%= if @user.group != "Admin" then  @user.group elsif  @department.nil? then "All" else @department end %> department info</span></h3>
            <div class="dropdown">
            <% if @user.group == "Admin"%>
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= if @department.nil? then  "Select Department" else @department end %> 
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <%= admin_dropdown_fil %>
  </div>
  <% end %>
</div>

            <br>
<div class="card-deck text-center ">
  <div class="card bg-primary text-white">
    <div class="card-block">
      <h4 class="card-title"><%= link_to "Unopened tickets", tickets_path(short_by: "02"), class: "homepageRedirectLink"%></h4>
      <p class="card-text text-white"><%= new_tickets_and_unopened(@user, @tickets,@department)%></p>
    </div>
  </div>
  <div class="card bg-info text-white">
    <div class="card-block">
      <h4 class="card-title"><%= link_to "In Progress", tickets_path(short_by: "04"), class: "homepageRedirectLink"%></h4>
      <p class="card-text text-white"><%= in_progress(@user, @tickets,@department)%></p>
    </div>
  </div>
  <div class="card bg-success text-white">
    <div class="card-block">
      <h4 class="card-title"><%= link_to "Solved", tickets_path(short_by: "03"), class: "homepageRedirectLink"%></h4>
      <p class="card-text text-white"><%= solved_tickets(@user, @tickets,@department)%></p>
    </div>
  </div>
      <div class="card bg-secondary text-white">
    <div class="card-block">
      <h4 class="card-title"><%= link_to "Won't Fix", tickets_path(short_by: "05"), class: "homepageRedirectLink"%></h4>
      <p class="card-text text-white"><%= wont_fix_tickets(@user, @tickets, @department)%></p>
    </div>
  </div>

<% else %>
    <div class="content">
    <br>
     <br>
      <br>
            <h3><span class="badge badge-secondary">Your tickets progress</span></h3>
            <br>
            
<div class="card-deck text-center ">
  <div class="card bg-primary text-white">
    <div class="card-block">
      <h4 class="card-title">You have opened</h4>
      <p class="card-text text-white"><%= new_tickets_and_unopened(@user, @tickets, @department)%></p>
    </div>
  </div>
  <div class="card bg-info text-white">
    <div class="card-block">
      <h4 class="card-title">In Progress</h4>
      <p class="card-text text-white"><%= in_progress(@user, @tickets, @department)%></p>
    </div>
  </div>
  <div class="card bg-success text-white">
    <div class="card-block">
      <h4 class="card-title">Have being Solved</h4>
      <p class="card-text text-white"><%= solved_tickets(@user, @tickets, @department)%></p>
    </div>
  </div>
    <div class="card bg-secondary text-white">
    <div class="card-block">
      <h4 class="card-title">Won't fix</h4>
      <p class="card-text text-white"><%=wont_fix_tickets(@user, @tickets, @department)%></p>
    </div>
  </div>

<% end %>

            <div class="line"></div>
<div class="home_page_table">
<table class="table table-dark">
<h3><span class="badge badge-secondary"><%= if @department.nil? then  "My Panel" else @department + " Panel" end %></span></h3>
<br>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Assign To</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each  do  |ticket| %>
      <tr>
        <td><%= ticket.user %></td>
        <td><%= ticket.title %></td>
        <% if  ticket.progress.username != nil %>
        <td><%= ticket.progress.username %></td>
        <%else%>
        <td> - </td>
        <% end %>
        <td><%= ticket.statusinfo %></td>
        <td><%= link_to 'Show', ticket, class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket), class: "btn btn-warning" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

</body>

</html>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Encrypted password</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Salt</th>
      <th>Group</th>
      <th>Email comfirmed</th>
      <th>Two factor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.email %></td>
        <td><%= user.mobile %></td>
        <td><%= user.salt %></td>
        <td><%= user.group %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/login.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Login</title>
  </head>
  <body>
    <center>
    <div class="Login_Form">
    <%= form_for(:user, id: 'forms', :url => {:controller => 'users', :action => 'verify'}, :html => { id: "forms" }) do |f| %> 
        <br>
        <br>
        <div class="text-center mt-5">
        <div class="login-form">
        <h2 id="Log_in" class="text-center">Log in</h2>       
        <div class="form-group">
        <%= f.text_field :username, id: "username", class: "form-control", placeholder: "Username"%>
        </div>
        <div class="form-group">
      <%= f.password_field :password, id: "login_password", class: "form-control", placeholder: "Password" %>
        </div>

        <div class="form-group">
              <%= f.submit :Login, class: 'btn btn-primary btn-block', id: "login_button"%>
        </div>
        <% flash.each do |type, msg| %>
          <div class="messages_erros">
            <strong><li><center><%= msg %></center></li></strong><br>
          </div>
        <% end %>
        <div class="clearfix">
      </div>
      <% end %>
      <br>
      <strong><a id="new_account" href="<%= new_user_path %>">Don't have an account? Sign up</a></strong><br>
      <strong><a id="restore_password" onclick="restore_form()" href="#">Forgotten password?</a></strong>
      <br>
      </div>
      <br>
      </div>
      </center>
      <script>
      function restore_form() {
      document.getElementById("new_account").remove();
      document.getElementById("login_password").remove();
      document.getElementById("Log_in").innerHTML = "Password Restore"
      document.getElementById("username").placeholder = "example@example.com"
      document.getElementById("login_button").value = "Send"
      document.getElementById('forms').action = "password_reset"
      document.getElementById('username').name = "user[email]"
      document.getElementById("restore_password").innerHTML = "Login"
      event.preventDefault()
      }
      </script>
  </body>
</html>

app/views/users/login_shield.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Login Shield</title>
  </head>
  <body>
    <center>
    <%= form_for(:user, :url => {:controller => 'users', :action => 'login_verify'}) do |f| %>
      <div class="container" id="shield">
      <strong>Code:</strong><br>
      <%= f.password_field :loginpass%>
      <br>
      <br>
      <%= f.submit :Login, class: 'log_in_button' %>
      <br>
      <% end %>
              <% flash.each do |type, msg| %>
          <div class="messages_erros">
            <strong><center><%= msg %></center><strong>
          </div>
        <% end %>
      <br>
      <p>Please Check your email inbox!</p>
      <br>
      <div id="resend">
      <p>You didn't recive the code? Please check your spam folder <br> OR: <%= button_to "Resend",  tryagain_users_path %></p>
      </div>
      <br>
      </div>
      <%= javascript_pack_tag "two_factor_resend_button" %>
      </center>
  </body>
</html>

app/views/users/mark_as_read.js.erb
document.getElementById("notifications_counter").textContent="0";

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/settings.html.erb
<div class="container-fluid">
<br>
<br>
<br>
<div class="text-center">
<div class="alert alert-primary text-center" role="alert">
    Security settings 
</div>
<br>
  <strong><%= link_to "Change Password", edit_user_path(session[:user_id]), class: "btn btn-outline-primary", id: "options" %></strong>
<br>
<br>
<strong><%= link_to "Change Email", users_email_update_path(:id => session[:user_id]), class: "btn btn-outline-primary", id: "options" %></strong>
<br>
<br>
<div class="alert alert-danger text-center" role="alert">
    Two factor authedication &nbsp;&nbsp;&nbsp;<i class="bi bi-question-diamond" title="You should have comfirm your email to use this action, After you enable this next time you will try to Log in a one time code will be send to your email" ></i>
</div>

<br>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'two_factor_switch'}) do |form| %>

<div class="btn-group btn-group-toggle  " data-toggle="buttons" id="home">
    <div class="custom-control custom-switch custom-switch-xl">
    <%= check_box_tag "two_factor", "active", @user.settings.two_factor, class: "custom-control-input", id: "customSwitch1"%>
    <%= label_tag 'customSwitch1', "", class: 'custom-control-label'%>
    </div>
  </div>
<br>
<br>
<div class="alert alert-secondary text-center" role="alert">
    General 
</div>
<strong><%= link_to "Add or update mobile number", users_update_mobile_path(:id => session[:user_id]), class: "btn btn-outline-primary", id: "options" %></strong>

</div>
</div>

    <%= form.submit "#{!@user.settings.two_factor}", class: "edit_profile", id: "save_detailes", :style => "display: none;" %>

<% end%>
 <%= javascript_pack_tag "two_factor_controll" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Encrypted password:</strong>
  <%= @user.encrypted_password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @user.mobile %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<p>
  <strong>Group:</strong>
  <%= @user.group %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>