config/routes.rb
Rails.application.routes.draw do
  get 'users/homepage'
  post 'users/homepage' => "users#homepage"

  get 'users/settings'
  post 'users/settings' => 'users#settings'

  get 'users/login_shield'
  post 'users/login_shield' => "users#login_shield"

  get '/', to: redirect('users/login')

  get 'users/login'
  post 'users/login' => 'users#login'
  
  get 'users/email_update'
  post 'users/email_update' => 'users#email_update'

  get 'tickets/tickets_tasks'
  post 'tickets/tickets_tasks' => 'tickets#tickets_tasks'

  get 'users/update_mobile'
  post 'users/update_mobile' => 'users/update_mobile'

  get 'users/password_recovery'
  post 'users/password_recovery' => 'users/password_recovery'

  resources :users do
    post :verify, on: :collection, as: :verify
    post :login_verify, on: :collection, as: :login_verify
    post :tryagain, on: :collection, as: :tryagain
    post :two_factor_switch, on: :collection, as: :two_factor_switch
    post :email_change, on: :collection, as: :email_change
    post :save_mobile_update, on: :collection, as: :save_mobile_update
    post :admin_filter, on: :collection, as: :admin_filter
    post :password_reset, on: :collection, as: :password_reset
    post :set_new_password, on: :collection, as: :set_new_password
    member do
      put "mark_as_read" => "users#mark_as_read"
      get :confirm_email
      get :change_forgoten_password
    end
  end

  resources :tickets do 
    post :watch, on: :collection, as: :watch
    post :unwatch, on: :collection, as: :unwatch
    post :imWorkingOnIt, on: :collection, as: :imWorkingOnIt
    post :solved, on: :collection, as: :solved
  end

  resources :progresss do
    post :add_subtasks, on: :collection, as: :add_subtasks
    post :assing_task, on: :collection, as: :assing_task
  end
  
  resources :comments do
      post :reply, on: :collection, as: :reply
      post :employee_reply, on: :collection, as: :employee_reply
  end

  get "/resend_eimail_confirmation" => "users#resend_eimail_confirmation", :as => "resend_eimail_confirmation"
  get "/log_out" => "users#logout", :as => "log_out"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<!-- <footer id="footer" class="bg-dark page-footer font-small blue fixed-bottom">

  <div class="footer-copyright text-center py-1 text-white">© 2021 Copyright
    <%= link_to "VKAutomate", "https://vkautomate.com/", target: :_blank %> 
     </div>

</footer>
-->

app/views/layouts/_navbar.html.erb
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
  <div class="wrapper">
  <div class="notifications_modal"">
<div class="modal fade" id="notifications" tabindex="-1" role="dialog" aria-labelledby="notificationsLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable" role="document">
    <div class="modal-content bg-dark" id="modal-content">
      <div class="modal-header ">
       <h5 class="modal-title " id="notificationsLabel">Notifications</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body">
        <% notifications = get_notification_info(User.find(session[:user_id]))%>
        <% if notifications != nil %>
        <% notifications.each do |notification|%>
        <div class="notifications_container">
        <h4 class="texting"><%= link_to notification.info, controller: "tickets", action: "show", id: notification.infoticketid %></h4>
      <div class="hr_line">
        <span>
          <%= distance_of_time_in_words(notification.created_at, Time.now)%>
          </span>
      </div>
      <br>
        </div>
        <% end %>
        <%end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
</div>
        <!-- Sidebar  -->
        <nav id="sidebar">
        <div class="email_warrning">
       <% if email_verifycation_check(session[:user_id]) %>
       <h4>
       <span class="badge badge-danger">You need to verify your email or you will be locked out! resend a verifycation email: <a href="<%= resend_eimail_confirmation_path%>">resend</a></span>
       </h4>
       <% end %>
       </div>
       <div class="links">
            <div class="sidebar-header">
                <h3>VKAutomate</h3>
                <strong>VKA</strong>
            </div>
            <ul class="list-unstyled components">
                <li class="active">
                    <a href=<%= users_homepage_path %> >
                        <i class="fas fa-home"></i>
                        Home
                    </a>
                </li>
                <li>
                    <a href=<%= new_ticket_path %> >
                        <i class="fas fa-briefcase"></i>
                        New Ticket
                    </a>
                    </li>
                     <% if User.find(session[:user_id]).group != "User"%>
                <li>
                    <a href=<%= tickets_path %> >
                        <i class="fas fa-image"></i>
                        Ticket History
                    </a>
                </li>
                <%end %>
                <li>
                    <a href=<%= users_settings_path %>>
                        <i class="fas fa-question"></i>
                        Settings
                    </a>
                </li>
                <li>
                    <a href=<%= log_out_path %>  class="ml-auto">
                        <i class="fas fa-paper-plane"></i>
                        Log Out
                    </a>
                </li>
            </ul>
            </div>
            <%= link_to mark_as_read_user_path(users_homepage_path), method: :put, remote: :true do%>
            <div class="sidebar-footer">
                &nbsp;  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#notifications">
        <i class="fa fa-bell"></i>
        <span class="badge badge-pill badge-warning notification" id="notifications_counter"><%= count_notifications%></span>
        </button>
     
                 
        </nav>
<% end %>


                <div id="content">

                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                    </button>
                </div>
                <br>
        </div>
    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
        document.g

/*                 $( '.links a' ).on('click', 
                    function (e) {
                     if (window.location.href != e.target.href) {
                       console.log(window.location.href)
                       console.log(e.target.href)
                       console.log("yess2")
                      $( '.links a' ).find( 'li.active' )
                      .removeClass( 'active' );
                       $( e.target.href).parent( 'li' ).addClass( 'active' );
                     } else {
                       console.log("yex")
                        $( this ).parent( 'li' ).addClass( 'active' );
        }}); */
       
    </script>


        <!-- Page Content  -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>  
  <body>
  <% unless session[:user_id] == nil || current_page?(users_login_path) || current_page?(new_user_path)  || current_page?(users_login_shield_url) || current_page?(users_path)%>
    <%= render "layouts/navbar" %>
<% end %>
    <%= yield %>

        <%= render "layouts/footer" %>

  </body>
</html>